### PR TITLE
GET support

### PR DESCRIPTION
**Pull request by helloguille**
### What does this PR do?

Adds support for GET requests.

### Related issues

#211 

### Checklist

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [ ] I have added or updated any relevant documentation
- [ ] I have added or updated any relevant tests

### CODE REVIEW

**Comment by mcollina** [comment]
Would you mind to add a test for this?

**Comment by helloguille** [comment]
@mcollina I'd love to, but I don't understand how I could validate if a GET request is being sent in the right format. 
I tried reading the existing tests, do you have any example from the existings test I could use as inspiration for this tests?

**Comment by helloguille** [comment]
Sorry about that. It was done automatically while experimenting with lerna.

I removed the last commits which were bumping versions.

Guillermo

**Comment by bmullan91** [comment]
@helloguille Thank you for the PR, I've gone ahead with this + tests in #410; thanks again for the head start 🙇

**Pull request closed without merging**
