### PR TITLE
Changed 'endpoint' to 'url' in example

### PR DESCRIPTION
**Pull request by heymartinadams**
### What does this PR do?

In your `graphql-hooks-memcache` example, you specified `endpoint` instead of `url` for the GraphQL Client. I believe it needs to be `url`.

### Checklist

- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md)
- [x] I have added or updated any relevant documentation
- [ ] I have added or updated any relevant tests

### CODE REVIEW

**Comment by Joezo** [comment]
You closed this before I could merge it :(

**Comment by heymartinadams** [comment]
Oh, geez, I’m so sorry (I already deleted the fork). I’m a noob when it comes to forks and PRs, so didn’t know what I was doing 😬

**Comment by heymartinadams** [comment]
Do you need me to create a new PR?

**Comment by Joezo** [comment]
@heymartinadams if you have the time, that'd be great 👍

**Pull request closed without merging**
