### PR TITLE
feat!: exclude client mutations from refetch condition

### PR DESCRIPTION
**Pull request by madshall**
Client's own options can be changed by a middleware which makes useQuery repeat the call

### What does this PR do?

It excludes client from comparison with a previous value in order to make a decision if a re-fetch is needed. Example: a middleware applies additional headers for specific queries only and restores them back to initial set after the request is complete. This runs `useEffect` hook again and it becomes an infinite loop.

### Related issues

none

### CODE REVIEW

**Comment by simoneb** [comment]
Thanks for the PR @madshall, and for submitting issue #1177. CI is red due to this change, can you please take a look? Also, it would be great to accompany this change with a test

**Comment by madshall** [comment]
@simoneb I've added the test and fixed the build. Could you please run the pipeline again?

**Review by simoneb — COMMENTED** [review]
This change makes sense to me, but it's also a breaking change and so I wonder if it makes sense to be included in the library, versus handled in user code. 

For instance, instead of modifying client's headers, can't you create a client with the headers you need?

**Comment by madshall** [comment]
The full use case is this:

Our app talks to multiple graphql servers that's why we don't use a provider, but initialize multiple clients and pass them to useQuery.

We have several middlewares - for dynamic headers (there are some headers which are unique for every request), for logging, error handling etc.

We use useManualQuery everywhere because useQuery gets stuck in a loop when client headers change (after every request).

I understand that technically it is a breaking change, but it really doesn't make sense to trigger a refresh based on allOpts. I'd really only expect it to be triggered when query or variables change, but not anything in the options, however changing that would be really a big deal. Client is the only object in the options that is a class instance and technically it is mutable and shouldn't trigger the hook. 

Would it be better if I put this change behind a feature flag, like an additional option for useQuery? Although it may look ugly having an option like `preventClientMutationsFromTriggeringTheHook`, right? Or maybe a client property, like `immutable=true` could drive this. What do you think?

**Comment by simoneb** [comment]
Ok yes I understand your point. Fair enough, I think we can cut a major just to remain semver compliant, but in practice I expect that this will not affect many users.

**Review by simoneb — APPROVED** [review]

**Pull request merged**
